import {describe,it,expect,beforeAll} from 'vitest';
import {data,loadNetwork,getNetwork,stationById,origins,departureCities,getOverview,parseState} from '../src/lib/network';
import type {HubId} from '../src/types';
const filters={type:'all',province:'',search:''} as const;
const originIds=new Set(origins.map(s=>s.id));
describe('passenger data integrity',()=>{
 beforeAll(async()=>{await loadNetwork()});
 it('deduplicates stations and geographic intervals',()=>{expect(new Set(data.stations.map(s=>s.id)).size).toBe(data.stations.length);expect(new Set(data.stations.map(s=>s.name)).size).toBe(data.stations.length);const keys=data.segments.map(s=>s.id);expect(new Set(keys).size).toBe(keys.length)});
 it('includes only published passenger coverage, with valid references',()=>{const ids=new Set(data.services.map(s=>s.id));for(const s of data.services){expect(s.passenger).toBe(true);expect(s.sourceUrl).toMatch(/^https:\/\/www\.crecc\.com\/huoche\//);expect(s.stations.some(id=>originIds.has(id))).toBe(true);expect(s.segmentIds.length).toBe(s.stations.length-1);for(const id of s.stations)expect(stationById.has(id)).toBe(true)}for(const s of data.segments){expect(s.serviceIds.length).toBeGreaterThan(0);expect(s.geometryAccuracy).toBe('approximate');expect(s.passengerCategories.length).toBeGreaterThan(0);s.serviceIds.forEach(id=>expect(ids.has(id)).toBe(true));if(!s.schematic){expect(s.geometrySource).toBe('OpenStreetMap');expect(data.physicalSources[s.osmSourceId].length).toBeGreaterThan(0)}else expect(['passenger-stop-corridor','reviewed-OSM-corridor-route','shared-passenger-corridor-route']).toContain(s.geometrySource);expect(s.name).not.toMatch(/货|动车所|专用|大秦|朔黄|瓦日|浩吉|神朔/);s.coverageStationIds.forEach(id=>expect(stationById.has(id)).toBe(true))}},30000);
 it('retains real WGS84 station positions and separate hubs',()=>{for(const s of data.stations){expect(s.latitude).toBeGreaterThan(18);expect(s.latitude).toBeLessThan(54);expect(s.longitude).toBeGreaterThan(73);expect(s.longitude).toBeLessThan(135);expect(s.coordinateSource).toBeTruthy()}expect(data.stations.filter(s=>s.isHub)).toHaveLength(origins.length);expect(data.networks.xuzhou.destinationStationIds).not.toEqual(data.networks['xuzhou-east'].destinationStationIds)});
 it.each(origins.map(s=>s.id) as HubId[])('computes direct destinations from the SAME service at %s',hub=>{const view=getNetwork(hub,filters);expect(view.destinations.length).toBeGreaterThan(0);expect(view.destinations.map(s=>s.id).sort()).toEqual(data.networks[hub].destinationStationIds);for(const d of view.destinations)expect(view.services.some(s=>s.stations.includes(hub)&&s.stations.includes(d.id))).toBe(true)});
 it.each(origins.map(s=>s.id) as HubId[])('highspeed and conventional partitions cover all destinations at %s',hub=>{const a=getNetwork(hub,filters),b=getNetwork(hub,{...filters,type:'highspeed'}),c=getNetwork(hub,{...filters,type:'conventional'});expect([...new Set([...b.destinations,...c.destinations].map(s=>s.id))].sort()).toEqual(a.destinations.map(s=>s.id).sort());expect(b.services.every(s=>'GCD'.includes(s.category))).toBe(true);expect(c.services.every(s=>!['G','C','D'].includes(s.category))).toBe(true)});
 it('province/search change map coverage as well as the directory',()=>{const all=getNetwork('xuzhou-east',filters),prov=getNetwork('xuzhou-east',{...filters,province:'shaanxi'});expect(prov.destinations.length).toBeGreaterThan(0);expect(prov.destinations.every(s=>s.province==='陕西')).toBe(true);expect(prov.segments.length).toBeLessThan(all.segments.length);expect(prov.stations.some(s=>s.id==='xuzhou-east')).toBe(true);const search=getNetwork('xuzhou-east',{...filters,search:'西安'});expect(search.destinations.every(s=>(s.name+s.city).includes('西安'))).toBe(true);expect(search.segments.length).toBeGreaterThan(0);expect(search.segments.length).toBeLessThan(all.segments.length)});
 it('unknown search creates no phantom connection',()=>{const v=getNetwork('xuzhou',{...filters,search:'不存在的车站'});expect(v.destinations).toHaveLength(0);expect(v.segments).toHaveLength(0);expect(v.stations.map(s=>s.id)).toEqual(['xuzhou'])});
});

describe('Jiangsu departure coverage',()=>{
 it('opens every validated province-index station without merging names',()=>{const jiangsu=origins.filter(s=>s.provinceId==='jiangsu');expect(new Set(jiangsu.map(s=>s.cityId)).size).toBe(13);expect(jiangsu).toHaveLength(86);expect(new Set(origins.map(s=>s.id)).size).toBe(origins.length);expect(new Set(origins.map(s=>s.name)).size).toBe(origins.length);for(const origin of origins){expect(stationById.get(origin.id)?.province).toBe(origin.province);expect(stationById.get(origin.id)?.city).toBe(origin.city);expect(data.networks[origin.id]).toBeDefined();expect(origin.verifiedServiceCount).toBeGreaterThan(0)}});
 it('city overview keeps all local stations separate before opening a network',()=>{for(const city of departureCities){const expected=origins.filter(s=>s.cityId===city.id);expect(getOverview(city.id).stations.map(s=>s.id).sort()).toEqual(expected.map(s=>s.id).sort());expect(getOverview(city.id).segments).toHaveLength(0)}});
 it('restores any supported departure station and rejects unsupported URL values',()=>{for(const origin of origins){const state=parseState('?station='+origin.id);expect(state.hub).toBe(origin.id);expect(state.city).toBe(origin.cityId)}expect(parseState('?station=not-a-station').hub).toBeNull();expect(parseState('?city=not-a-city').city).toBeNull()});
 it('keeps Jiangsu Suzhou and Anhui Suzhou in separate cities and quarantines a wrong-province catalogue entry',()=>{
  const jiangsu=origins.find(s=>s.name==='苏州')!,anhui=origins.find(s=>s.name==='宿州')!;
  expect(jiangsu.cityId).not.toBe(anhui.cityId);expect(jiangsu.id).not.toBe(anhui.id);
  expect(parseState('?station='+anhui.id).city).toBe('anhui-suzhou');
  expect(origins.some(s=>s.name==='牛车河'&&s.provinceId==='shandong')).toBe(false);
  expect(origins.some(s=>s.name==='向阳'&&s.provinceId==='henan')).toBe(false);
  expect(origins.some(s=>s.name==='石城'&&s.provinceId==='jiangxi')).toBe(false);
 });
});
