import {ArrowUpRight,Route,TrainFront,ArrowRight,LockKeyhole,Search,MapPin} from 'lucide-react';
import type {Filters,HubId,CityId} from '../types';
import type {ViewNetwork} from '../lib/network';
import {departureCities,origins} from '../lib/network';
export function Header({onSwitch,onAbout,active,onHome}:{onHome:()=>void;onSwitch:()=>void;onAbout:()=>void;active:boolean}){return <header className="site-header"><a className="brand" href="?" onClick={e=>{e.preventDefault();onHome()}}><Route size={27} strokeWidth={1.6}/><span>沿线<small>Railbound</small></span></a><div className="header-caption">一座车站，无数种出发。</div><nav><button onClick={onAbout}>关于沿线 <ArrowUpRight size={15}/></button>{active&&<button className="switch-button" onClick={onSwitch}>切换中心站 <ArrowRight size={16}/></button>}</nav></header>}
export function CityBar({city,onCity,onHub}:{city:CityId|null;onCity:(selected:CityId|null)=>void;onHub:(id:HubId)=>void}){
 const provinces=[...new Set(origins.map(s=>s.province))];
 const stations=origins.filter(s=>s.cityId===city).sort((a,b)=>Number(a.tier==='local')-Number(b.tier==='local')||b.verifiedServiceCount-a.verifiedServiceCount);
 return <div className="city-bar"><label className="city-picker"><MapPin size={17}/><span>出发城市</span><select aria-label="出发城市" value={city||''} onChange={e=>onCity(e.target.value||null)}><option value="">选择城市</option>{provinces.map(p=><optgroup key={p} label={p}>{departureCities.filter(c=>origins.some(s=>s.cityId===c.id&&s.province===p)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup>)}</select></label>{city?<div className="hub-picker"><span>选择经过站点</span><div className="hub-options">{stations.map(s=><button key={s.id} onClick={()=>onHub(s.id)}><TrainFront size={16}/>{s.name}站<ArrowRight size={14}/></button>)}</div></div>:<p>先选择出发城市，再从一座车站展开客运网络。<span>当前开放 {departureCities.length} 个城市</span></p>}</div>
}
export function FilterBar({view,filters,onChange}:{view:ViewNetwork;filters:Filters;onChange:(v:Partial<Filters>)=>void}){return <div className="filters"><div className="fixed-city"><MapPin size={15}/><span>出发城市</span><strong>{view.hubStation.city}</strong></div><div className="required-filter"><span>经过站点 <LockKeyhole size={12}/></span><strong>{view.hubStation.name}站</strong><span className="signal"/></div><label className="select-filter"><span>列车类型</span><select aria-label="列车类型" value={filters.type} onChange={e=>onChange({type:e.target.value as Filters['type']})}><option value="all">全部客运</option><option value="highspeed">高速动车</option><option value="conventional">普速</option></select></label><label className="select-filter"><span>目的地区域</span><select aria-label="目的地区域" value={filters.province} onChange={e=>onChange({province:e.target.value})}><option value="">全部地区</option>{view.provinces.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="search-filter"><Search size={18}/><input aria-label="搜索可直达城市或车站" placeholder="搜索可直达城市或车站" value={filters.search} onChange={e=>onChange({search:e.target.value})}/>{filters.search&&<button aria-label="清除搜索" onClick={()=>onChange({search:''})}>×</button>}</label></div>}
