import {useEffect,useRef} from 'react';
import {ArrowLeft,ArrowUpRight,Route,TrainFront,ArrowRight,LockKeyhole,Search,MapPin} from 'lucide-react';
import type {Filters,HubId,CityId} from '../types';
import type {ViewNetwork} from '../lib/network';
import type {DepartureSelection} from '../lib/departureIndex';
import type {StationGroup} from '../lib/stationChoiceIndex';
import {departureCities,departureIndex,intercityIndex,stationChoiceIndex} from '../lib/network';
export function Header({onSwitch,onAbout,active,onHome}:{onHome:()=>void;onSwitch:()=>void;onAbout:()=>void;active:boolean}){return <header className="site-header"><a className="brand" aria-label="沿线 Railbound" href="?" onClick={e=>{e.preventDefault();onHome()}}><Route size={27} strokeWidth={1.6}/><span>沿线<small>Railbound</small></span></a><div className="header-caption">一座车站，无数种出发。</div><nav><button onClick={onAbout}>关于沿线 <ArrowUpRight size={15}/></button>{active&&<button className="switch-button" onClick={onSwitch}>切换中心站 <ArrowRight size={16}/></button>}</nav></header>}
export function CityBar({selection,group,onGroup,onScope,onCity,onHub}:{group:StationGroup|null;onGroup:(group:StationGroup|null)=>void;selection:DepartureSelection;onScope:(region:string|null,province:string|null)=>void;onCity:(selected:CityId|null)=>void;onHub:(id:HubId)=>void}){
 const {region,province,city}=selection;
 const choices=stationChoiceIndex.city(city),stations=choices.all,activeGroup=choices.groups.find(g=>g.id===group);
 const groupHeading=useRef<HTMLHeadingElement>(null),groupButtons=useRef<Partial<Record<StationGroup,HTMLButtonElement|null>>>({}),previousGroup=useRef(group);
 useEffect(()=>{if(group)groupHeading.current?.focus();else if(previousGroup.current)groupButtons.current[previousGroup.current]?.focus();previousGroup.current=group},[group]);
 const stationButton=(s:typeof stations[number])=><button key={s.id} onClick={()=>onHub(s.id)}><TrainFront size={16}/>{s.name}站<ArrowRight size={14}/></button>;
 return <div className="city-bar">
  <div className="departure-index" role="group" aria-label="选择出发地">
   <label className="index-picker"><span>出发区域</span><select aria-label="出发区域" value={region||''} onChange={e=>onScope(e.target.value||null,null)}><option value="">选择区域</option>{departureIndex.regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
   <label className="index-picker"><span>出发省份</span><select aria-label="出发省份" disabled={!region} value={province||''} onChange={e=>onScope(region,e.target.value||null)}><option value="">{region?'选择省份':'先选区域'}</option>{departureIndex.provincesIn(region).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <label className="index-picker city-picker"><span>出发城市</span><select aria-label="出发城市" disabled={!province} value={city||''} onChange={e=>{const selected=e.target.value;if(selected)onCity(selected);else onScope(region,province)}}><option value="">{province?'选择城市':'先选省份'}</option>{departureIndex.citiesIn(province).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  </div>
  {city&&<p className="index-hint index-summary">{departureIndex.cities.get(city)?.name} · {stations.length} 座独立车站<span>选择下方车站，展开全国直达网络</span></p>}
  {city?<div className={`hub-picker ${activeGroup?'intercity-picker':''}`}>{activeGroup?<div className="intercity-navigation"><button onClick={()=>onGroup(null)} aria-label="返回全部车站"><ArrowLeft size={14}/>全部车站</button><h2 ref={groupHeading} tabIndex={-1}>{activeGroup.name} <small>{activeGroup.stations.length} 座独立车站</small></h2></div>:<span>选择经过站点{choices.primary.length>12&&<small>滚动查看全部车站</small>}</span>}{activeGroup?<div id={`${activeGroup.id}-panel`} className="intercity-stations" role="region" aria-label={activeGroup.id==='intercity'?'城际车站':'市内及周边小站'}>{activeGroup.sections.map(section=><section key={section.id} className="intercity-line"><h3>{section.name}</h3><div className="hub-options">{section.stations.map(s=><div key={s.id} className="intercity-stop">{stationButton(s)}{activeGroup.id==='intercity'&&intercityIndex.memberships.get(s.id)!.lines.length>1&&<small>{intercityIndex.memberships.get(s.id)!.lines.slice(1).map(l=>l.name).join(' · ')}</small>}</div>)}</div></section>)}</div>:<div className="hub-options">{choices.groups.map(g=><button key={g.id} ref={el=>{groupButtons.current[g.id]=el}} className="intercity-entry" onClick={()=>onGroup(g.id)} aria-label={g.name} aria-controls={`${g.id}-panel`} aria-expanded={false}><Route size={16}/><span>{g.name}<small>{g.stations.length} 站</small></span><ArrowRight size={14}/></button>)}{choices.primary.map(stationButton)}</div>}</div>:<p className="index-hint">{province?'选择城市，再从一座车站出发。':region?'选择省份，继续寻找出发城市。':'按区域、省份、城市，找到你的出发地。'}<span>已开放 {departureCities.length} 个城市</span></p>}
 </div>
}

export function FilterBar({view,filters,onChange}:{view:ViewNetwork;filters:Filters;onChange:(v:Partial<Filters>)=>void}){return <div className="filters"><div className="fixed-city"><MapPin size={15}/><span>出发城市</span><strong>{view.hubStation.city}</strong></div><div className="required-filter"><span>经过站点 <LockKeyhole size={12}/></span><strong>{view.hubStation.name}站</strong><span className="signal"/></div><label className="select-filter"><span>列车类型</span><select aria-label="列车类型" value={filters.type} onChange={e=>onChange({type:e.target.value as Filters['type']})}><option value="all">全部客运</option><option value="highspeed">高速动车</option><option value="conventional">普速</option></select></label><label className="select-filter"><span>目的地区域</span><select aria-label="目的地区域" value={filters.province} onChange={e=>onChange({province:e.target.value})}><option value="">全部地区</option>{view.provinces.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="search-filter"><Search size={18}/><input aria-label="搜索可直达城市或车站" placeholder="搜索可直达城市或车站" value={filters.search} onChange={e=>onChange({search:e.target.value})}/>{filters.search&&<button aria-label="清除搜索" onClick={()=>onChange({search:''})}>×</button>}</label></div>}
