import {X,ArrowUpRight,Check,MapPin} from 'lucide-react';
import {data,stationById,serviceById,originById} from '../lib/network';
import type {ViewNetwork} from '../lib/network';
import type {RailwaySegment,Station} from '../types';
export function Details({station,segment,view,onClose,onDepart,inactive=false}:{inactive?:boolean;station?:Station;segment?:RailwaySegment;view:ViewNetwork;onClose:()=>void;onDepart?:(id:string)=>void}){
 if(!station&&!segment)return null;
 const services=station?view.services.filter(s=>s.stations.includes(station.id)):view.services.filter(s=>segment!.serviceIds.includes(s.id));
 const categories=[...new Set(services.map(s=>s.category))];
 const covered=segment?.coverageStationIds.map(id=>stationById.get(id)!).filter(s=>view.stations.some(v=>v.id===s.id))||[];
 return <aside className="detail-panel" aria-label="地图详情"><div className="detail-top"><span>{station?'沿线车站':'客运联系区段'}</span><button aria-label="关闭详情" onClick={onClose}><X size={18}/></button></div><h3>{station?`${station.name}${station.name.endsWith('站')?'':'站'}`:segment?.name||'客运轨道区段'}</h3>{station&&<p className="location"><MapPin size={13}/> {station.province} · {station.city}</p>}{station?.formerNames?.length&&<p className="detail-note">曾用名：{station.formerNames.join('、')}站</p>}<div className="direct-status"><Check size={17}/>{inactive?'客运车站':station?.id===view.hubStation.id?'当前中心站':station?(services.length?`从${view.hubStation.name}可直达`:'地理路径参考站'):'公开客运服务覆盖'}</div>{!inactive&&<><div className="detail-row"><span>匹配客运类型</span><strong>{categories.join(' / ')||'—'}</strong></div><div className="detail-row"><span>收录服务</span><strong>{services.length} 个</strong></div><div className="detail-sources"><p>示例客运服务</p>{services.slice(0,3).map(s=><a key={s.id} href={serviceById.get(s.id)!.sourceUrl} target="_blank" rel="noreferrer">{s.trainNumber}<ArrowUpRight size={12}/></a>)}</div></>}{inactive&&<p className="detail-note">先选择出发城市与经过站点，再查看客运直达关系。</p>}{segment&&<><div className="segment-stops"><p>当前匹配的经停联系</p><span>{covered.slice(0,8).map(s=>s.name).join(' · ')}{covered.length>8?' …':''}</span></div>{!segment.schematic&&<a className="osm-source" href={`https://www.openstreetmap.org/${data.physicalSources[segment.osmSourceId][0]}`} target="_blank" rel="noreferrer">查看来源轨道走廊<ArrowUpRight size={12}/></a>}<p className="detail-note">{segment.schematic?'此段为客运走廊示意。地图会合并相近线路，显示形状与列车实际径路可能不同。':'参考区段来自 OpenStreetMap 铁路轨道。地图上相近线路已合并，显示线不代表已核验的逐车次运行径路。'}</p></>}{station&&originById.has(station.id)&&(inactive||station.id!==view.hubStation.id)&&<button className="detail-depart" onClick={()=>onDepart?.(station.id)}>从{station.name}站出发 <ArrowUpRight size={15}/></button>}{station&&!originById.has(station.id)&&<p className="detail-note">这座车站的出发网络尚未开放，正在按城市逐步拓展。</p>}</aside>
}
